### ISSUE TITLE
Fix broken link to build environment

### ISSUE THREAD

**Issue by kulp** [makestuff/libfpgalink#35]
When trying to set up libfpgalink on a new system I found that the link in the README to makestuff (http://bit.ly/makestuff) is broken, meaning it is quite difficult to figure out how to build.

I did manage by trolling through gists to find an old version of makestuff that works enough to build (which I have since lost the link to). Please at least update the README to point to a working `makestuff` or more ideally, provide a git repository of the makestuff code to prevent further bitrot.

Thank you.

**Comment by makestuff** [comment]
Sorry that README has obviously suffered from bit-rot over the years. I'll see if I can fix it. Meanwhile, the best way to build the library is to use one of the quickstarts, documented on the wiki: https://gist.github.com/makestuff/7829484#file-nexys2-howto-L8

**Comment by kulp** [comment]
Although I have not tested it, it looks as though #38 addressed the current issue, so I will close this.
