### ISSUE TITLE
spartan 6 ava6slx9(spartan 6 xc6slx9)

### ISSUE THREAD

**Issue by jackobian** [makestuff/libfpgalink#37]
Sir I have the following schematic of xilinx spartan 6 development broad, i have tried to connect it through usb cypress but always failed.
this is the schematic
[AVA6SLXBoardSchematic-v2.pdf](https://github.com/makestuff/libfpgalink/files/2239053/AVA6SLXBoardSchematic-v2.pdf)
and the error message 
[new  2.txt](https://github.com/makestuff/libfpgalink/files/2239055/new.2.txt)

**Comment by makestuff** [comment]
Don't ask for help here. Use the mail group.

**Comment by jackobian** [comment]
what is mail group Sir?

**Comment by makestuff** [comment]
You can find it on the [wiki](https://github.com/makestuff/libfpgalink/wiki/FPGALink), or by googling "fpgalink mail group".
